# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee4a678ce87ae0e83a311cf85ceedd8b378aa864be7b445bba09d645b57e7daacaa9053720572129f7811bb838a80e105fbab4d45fd9bb3a165ff90b01e958c

test:
  secret_key_base: 8a52ae86e1e38b36fa8a23e6803a437935593d9df120e9e510bbdcce8adbb8df0a38729fb22f477498c5f290bdf97c9bfb351ee943995a2200d3bb6d0f7148bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
